---
- hosts: loadBalancer
  become: true
  tasks:
  - name: install web components
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - nginx
      - python-pip
      - python-virtualenv